[package]
name = "manual-future"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
tokio = { version = "1.8.1", features = ["full"] }
